# Generated by Django 4.2.5 on 2023-09-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='stand',
            new_name='standes',
        ),
    ]
