# Generated by Django 4.2.6 on 2023-10-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_stand_reserva_standes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='localizacao',
            field=models.CharField(max_length=200, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
    ]
